#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x8A74A50D3341CBBE (evgeny.burovskiy@gmail.com)
#
Name     : scipy
Version  : 0.19.0
Release  : 63
URL      : http://pypi.debian.net/scipy/scipy-0.19.0.zip
Source0  : http://pypi.debian.net/scipy/scipy-0.19.0.zip
Source99 : http://pypi.debian.net/scipy/scipy-0.19.0.zip.asc
Summary  : SciPy: Scientific Library for Python
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause MIT Qhull
Requires: scipy-python
Requires: libc-bin
BuildRequires : numpy
BuildRequires : openblas
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Here's what is available (all in double precision):
LSODE
LSODES
LSODA
LSODAR
LSODI
LSOIBT

%package python
Summary: python components for the scipy package.
Group: Default

%description python
python components for the scipy package.


%prep
%setup -q -n scipy-0.19.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1492543816
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-semantic-interposition "
python2 setup.py build -b py2 --fcompiler=gnu95
python3 setup.py build -b py3 --fcompiler=gnu95

%install
export SOURCE_DATE_EPOCH=1492543816
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
